all:
	make -C slab/src
	make -C cjson/src
	make -C gb28181/src
	make -C share/src
	make -C preview/src

clean:
	cd slab/src;make clean
	cd cjson/src;make clean
	cd gb28181/src;make clean
	cd share/src;make clean
	cd preview/src;make clean

